services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ./ollama:/root/.ollama
    restart: unless-stopped
    gpus: all
    environment:
      - OLLAMA_KEEP_ALIVE=-1
      - OLLAMA_SCHED_SPREAD=1

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    ports:
      - 8080:8080
    volumes:
      - ./open-webui:/app/backend/data
    environment:
      - WEBUI_LOG_LEVEL=info
      - OPENAI_API_BASE_URL=http://vllm:8000/v1
      - OPENAI_API_KEY=EMPTY
      - ENABLE_OPENAI_API=true
      - DEFAULT_MODELS=Qwen/Qwen2.5-32B-Instruct
      - OPENAI_API_CONFIGS=[{"name":"vLLM","base_url":"http://vllm:8000/v1","api_key":"EMPTY","models":["Qwen/Qwen2.5-32B-Instruct"]}]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
